version: "3"
services:
  frontend-programmer-ia:
    build: ./frontend
    ports:
      - "4500:80"
    depends_on:
      - backend-programmer-ia
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - programmer_ia_network

  backend-programmer-ia:
    build: ./backend
    ports:
      - "9600:8000"
    depends_on:
      - mongo-programmer-ia
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    environment:
      - OPENAI_SECRET_KEY=${OPENAI_SECRET_KEY}
      - DEEPSEEK_SECRET_KEY=${DEEPSEEK_SECRET_KEY}
      - GEMINI_SECRET_KEY=${GEMINI_SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=True
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - programmer_ia_network

  mongo-programmer-ia:
    image: mongo:7.0
    container_name: mongo-programmer-ia
    restart: unless-stopped
    volumes:
      - ./DataBase/mdb_programmer_ia.js:/docker-entrypoint-initdb.d/mdb_programmer_ia.js:ro
      - mongo_programmer_ia:/data/db
    ports:
      - "27019:27017"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - programmer_ia_network

networks:
  programmer_ia_network:
    driver: bridge    

volumes:
  mongo_programmer_ia:
    driver: local # Utiliza un volumen persistente local
