version: "3.9"
services:
  frontend:
    build: ./frontend-angular
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./backend-django
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - DJANGO_SETTINGS_MODULE=mi_proyecto.settings
      - MONGO_URI=mongodb://mongo:27017/tu_base

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
